apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    extensions:
    - extension:
        last-update: Wed, 15 Dec 2021 16:09:09 CET
        provider: minikube.sigs.k8s.io
        version: v1.24.0
      name: cluster_info
    server: https://192.168.184.3:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 15 Dec 2021 16:09:09 CET
        provider: minikube.sigs.k8s.io
        version: v1.24.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: ""
    user: sa-user
  name: sa-context
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluSmZTazAyY0ZKMlNWVnlUV0Z1TXpremRFUk5UMk40ZGpabFZ6RjBVakpIVjNWcWVYRmFWSG96U25NaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dFkyUTJlR3dpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbVk0TUdReFpqSm1MV1V5WW1NdE5EZzBNUzA1TXpNNUxXUXhaRFEwTkdWak16VXpPU0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEuQmFWVFhQTDU2YU50amdUV09TeVNjMzk1cFZaNmd6YmNYeFNHMkxlQ1BZdmp5bzhIbGNzVkZxRXBQckx4MW03TnpSald0d212eFhBVHVSMl9lRzF2bEo3dHAyd05Oak43U3F2a1laWXNMZzZRSTQtMk5OT2RUUTY1VVhZdFB6QURrNzBaeWxkTHFyZ21TX3hfX2UwbnZ3ckZha08yX1dmcklYc0RETmduYkdsbWxFZWttb3dFYlgtV01RcDdzYnBvSlNNWjFMNFNEN055M09EWm9Hb0t2cmF4OWxmWUl5eHBVcU9jUkpDR2xNZWxfRlhGWGJTZnl3cXhRZjA5TVMzdGRyME1xMkhxdVRYeXRTSjJESzRlWU1lYk84Y25nWURTci1lTDZXdWhzWTBtb2NRRUI4bEdZTWFFcHNGNWJ5UXg3Tlgxd0t5Rm0yZGI4eGtSY0VGeFNR
- name: sa-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InJfSk02cFJ2SVVyTWFuMzkzdERNT2N4djZlVzF0UjJHV3VqeXFaVHozSnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tY2Q2eGwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY4MGQxZjJmLWUyYmMtNDg0MS05MzM5LWQxZDQ0NGVjMzUzOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.BaVTXPL56aNtjgTWOSySc395pVZ6gzbcXxSG2LeCPYvjyo8HlcsVFqEpPrLx1m7NzRjWtwmvxXATuR2_eG1vlJ7tp2wNNjN7SqvkYZYsLg6QI4-2NNOdTQ65UXYtPzADk70ZyldLqrgmS_x__e0nvwrFakO2_WfrIXsDDNgnbGlmlEekmowEbX-WMQp7sbpoJSMZ1L4SD7Ny3ODZoGoKvrax9lfYIyxpUqOcRJCGlMel_FXFXbSfywqxQf09MS3tdr0Mq2HquTXytSJ2DK4eYMebO8cngYDSr-eL6WuhsY0mocQEB8lGYMaEpsF5byQx7NX1wKyFm2db8xkRcEFxSQ
